### ISSUE TITLE
gradients...

### ISSUE THREAD

**Issue by Mark-Mark** [caleb531/jcanvas#186]
I was just working with gradients. Let's say I want to create a gradient and apply it to ten layers. The layers are all over the canvas and can be moved via other Javascript code. This is not possible, correct me if I am wrong, because the X and Y of the gradient are relative to the layer.

Reading more I see the solution for animating layers with gradients. For the case above a lot of repeat code. 

How about two new properties in the gradient or the layer like fillRelativeX and fillRelativeY or some other suitable names. Then if true, the x and y of the gradient become relative to the x and y of the layer.

On a side note, is there an offline file of the documentation for jCanvas?

Caleb, thanks for creating and maintaining jCanvas.

**Comment by caleb531** [comment]
This should be already possible. See the second example for the "Animating Layers with Gradients" section:
http://calebevans.me/projects/jcanvas/docs/gradients/#animating-layers-with-gradients

You'll discover that function layers are quite handy for dealing with this particular problem.

To answer your other question, the raw jCanvas docs are available for download from Github:
https://github.com/caleb531/jcanvas-docs

Caleb

**Comment by Mark-Mark** [comment]
Thanks for the response. 

The second example was the one I was referencing.
They are handy but, it would be much simpler, smoother design, less code, to work with two properties. 

My2c.

As to the docs. unless I am missing something that is many files, in php. I was looking for a PDF or text file, etc., something I could read/search off line.

**Comment by caleb531** [comment]
I suppose I *could*, but the behavior of such properties might be ambiguous depending on the drawing (rectangle, circle, polygon, path, *etc.*).

The docs are only available as they are (`.php`). Therefore, I might recommend finding a Markdown Previewer most suitable to your liking (since Markdown can render plain HTML). Not everything will be renderable, of course, but the majority of the documentation should render just fine in Markdown.

Caleb
