### ISSUE TITLE
drawLine and rotate...

### ISSUE THREAD

**Issue by Mark-Mark** [caleb531/jcanvas#188]
Hi,

We are using drawLine to create polygons that have unequal sides. Works great.

We allow the user to set the rotation. In jCanvas the rotation for this lines is ... around an axis point I am not sure from where. I was hoping the axis point would be the center of the polygon based on the line point extents.

We also rotate text and that works as expected. The alignment is set to center and the text rotates on the center of the text axis.

Am I missing something?

Cheers,

Mark

**Comment by caleb531** [comment]
Calculating the center of a path would be to inefficient for jCanvas to do automatically. Instead, you'll need to set the `x` and `y` properties on the path. You'll also need to subtract the `x` and `y` values for the respective coordinates, because the entire path will now be offset by the (x, y) you specify.

Text in jCanvas, is centered horizontally and vertically by default. To change the vertical alignment, set the `baseline` property ([documented here](http://calebevans.me/projects/jcanvas/docs/properties/#baseline)).

**Comment by Mark-Mark** [comment]
OK, so I need to set x and y, not x1,x2, ... and then calculate the x1,x2,... to be offset from x and y? And of course the same for y1,y2...

Then if I set the rotate property, the polygon will rotate on the x/y point?

As to the text. It is working as expected = great.

**Comment by caleb531** [comment]
Yes, your assumption (re: rotating paths) is correct. :)

**Comment by Mark-Mark** [comment]
Set fromCenter true, set x and y to the center of the polygon, recalculated x1..xn and y1..yn to be offset from x/y, set rotation value, worked great.

Thanks Caleb
