### ISSUE TITLE
drawLine, mouseover, IE bug

### ISSUE THREAD

**Issue by djnolder** [caleb531/jcanvas#229]
canvas.drawLine({
    layer: true,
    strokeStyle: '#FF00FF',
    strokeWidth: 50,
    x1: 25, y1: 0,
    x2: 25, y2: 50,
    mouseover: function(layer){
        console.log('x');
    },
});

Put simply. IE does not execute the mouseover effect. All other browsers appear to work fine, as well as other methods in IE.

**Comment by caleb531** [comment]
Does the JavaScript Console in IE show any errors after running that code?

**Comment by djnolder** [comment]
Doesn't throw an error that I saw.

**Comment by caleb531** [comment]
Which versions of IE have you tested? (and obviously, which versions work / don't work)

**Comment by djnolder** [comment]
I mainly tested in edge.

**Comment by caleb531** [comment]
Okay, good news: I feel quite confident what is causing the issue here.

Most modern browsers (like Chrome) support two important methods for event detection on the canvas: `isPointInPath` and `isPointInStroke`. However, all canvas-supporting versions of IE have only supported `isPointInPath`, and *not* `isPointInStroke`. This is a browser issue that I am unable to fix or polyfill.

The reason this isn't an issue for most methods is because almost all methods have fill regions. A straight line like the one you've drawn, however, has no fill (because it consists of only one line segment).

Therefore, as I see it, you have two options:

1. The simplest option: choose a different method for drawing your line (based on the drawing that code produces, you could probably get away with using `drawRect`)
2. The probably-better option: redraw the path using drawLine, except make your line segments form the edges of the line you want to draw, rather than the whole thing; in other words, drawing a rectangle with drawRect or more or less equivalent to drawing four connected line segments with `drawLine`

I hope that helps. Let me know if you have any questions. :)
