### ISSUE TITLE
Difference in JCanvas 14 vs new versions

### ISSUE THREAD

**Issue by abwaters** [caleb531/jcanvas#237]
I don't know whether i'm missing something here or not.  I've done a bit of research but I can't figure out why the scaling/cropping rectangles on drawImage don't work they way they used to...i'm not sure if its a bug or if it is a change in behavior but i'm hoping you can help me with this.

Version 14 is the last I've seen where it works.  I've tryed v15 and v16 with poor results.  See the two examples below for a simple test case I created to demonstrate the problem.

Working on v14: [http://jcanvastest.abwaters.com.s3-website-us-east-1.amazonaws.com/old/](http://jcanvastest.abwaters.com.s3-website-us-east-1.amazonaws.com/old/)

Fails on v16: [http://jcanvastest.abwaters.com.s3-website-us-east-1.amazonaws.com/new/] (http://jcanvastest.abwaters.com.s3-website-us-east-1.amazonaws.com/new/)

Can you tell me what i'm missing?

**Comment by caleb531** [comment]
Off the top of my head, I would suggest setting `cropFromCenter` to `true` or `false`. Granted, I don't know what you have it set to, much less if you've set it at all, but I feel generally confident that setting `cropFromCenter` to either `true` or `false` will solve the offsetting (that is, if either of those values doesn't work, the other value most likely will). :)

Caleb

**Comment by abwaters** [comment]
The code is the same for both.  Look at source.

**Comment by caleb531** [comment]
Really? That's not what I'm seeing in the source on master:
https://github.com/caleb531/jcanvas/blob/master/jcanvas.js#L3845

Where are you looking?

Caleb

**Comment by abwaters** [comment]
In my source for the old and new versions of jcanvas they are the same.
Both have cropfromcenter set to false.

**Comment by caleb531** [comment]
Alright, then. I recommend you use the newest version of jCanvas (v16.04.01) and use `cropFromCenter: true` in your code.

**Comment by abwaters** [comment]
Did the logic change then?  cropFromCenter: false doesn't work any longer?

**Comment by abwaters** [comment]
The following code works in the old version but not in the new version.  
I'm trying to figure out if there was a fundamental change (intentional) 
in the newer version or if there is a bug?

c.drawImage({
             layer: true,
             name: did.toString(),
             groups: ['layer1'],
             source: DOMINO_PATH,
             x: x,
             y: y,
             width: w,
             height: h,
             sx: sx,
             sy: sy,
             sWidth: sw,
             sHeight: sh,
             cropFromCenter: false,
             fromCenter: false
             }) ;

**Comment by caleb531** [comment]
Looking through the logs and comparing the diffs, I suspect that the logic might have changed at one point, or perhaps the old behavior you're expecting was actually a bug that is now fixed. It's difficult to say for sure—since this issue covers two years of commits—but I still feel that the current behavior is correct.

Therefore, I will ask again: what happens if you set `cropFromCenter: true` in your code? :)

Caleb

**Comment by abwaters** [comment]
It doesn't work if I do that.  I'm calculating my coordinates correctly 
for the top/left of the image.  I've spent quite a bit of time doing 
that and the logic works in several other frameworks...I can modify the 
javascript to work with cropFromCenter but I was trying to rule out a 
bug which it definitely seems like is there. My top-left on the location 
in the source image is correct and so are my width and heights.

If you are saying there is a bug that won't be addressed then i'll go 
with that...maybe even spend more time looking at the underlying code 
but its getting to the point where i need some of your upgrades, 
especially the webkitImageSmoothingEnabled changes for iPads but I need 
to know what the best approach is...if I can help you address a bug then 
i'll put the energy in there...if you have a working sample in the new 
code where cropFromCenter: false works, then let me examine that and see 
what i'm missing.

Thanks Caleb!  If I hadn't said it before, jCanvas is awesome!

**Comment by abwaters** [comment]
*sigh*

I just tried cropFromCenter: false in the new code and it worked. I'm 
not sure I understand intuitively why but...it worked.  My 
apologies...not critical but if you can explain why this works since i'm 
providing the upper-left of the crop-from region rather than the center, 
I would appreciate it.

**Comment by caleb531** [comment]
Why does it work even though it seems unintuitive? I suppose because I was thinking about it differently, albeit correctly or at least consistently (and I'll try to prove it with examples.

Let me begin by explaining `fromCenter`, which `cropFromCenter` is based off of. Note that the white square is fixed at the green square's `x` and `y` coordinates.

When `fromCenter` is set to `true`, the shape's `x` and `y` coordinates (*i.e.* the position of the white square in this case) lie at the center of the shape.

![fromCenter: true](https://cloud.githubusercontent.com/assets/872474/14577685/db1315c2-032b-11e6-8c9d-6185561e26f4.png)

When `fromCenter` is set to `false`, the shape's `x` and `y` coordinates now lie at the top-left corner of the shape.

![fromCenter: false](https://cloud.githubusercontent.com/assets/872474/14577699/039db65a-032c-11e6-904a-c267c72fe179.png)

Similarly, when `cropFromCenter` is set to `true`, the shape's `sx` and `sy` coordinates lie at the center of the cropped region. Note for now that the topmost clownfish is partially showing in the top-left corner of this cropped region.

![cropFromCenter: true](https://cloud.githubusercontent.com/assets/872474/14577706/30fa5266-032c-11e6-9ec0-f547ea77bc29.png)

However, when `cropFromCenter` is set to `false`, the shape's `sx` and `sy` coordinates now lie at the top-left corner of the cropped region (which is why the white square is on the topmost clownfish).

![cropFromCenter: false](https://cloud.githubusercontent.com/assets/872474/14577718/6eaa4832-032c-11e6-908a-dd7d0623a0c3.png)

The reason I can say `cropFromCenter` works correctly is because, as I've demonstrated, its behavior is consistent with that of `fromCenter`.

Is this making more sense? :)
Caleb

**Comment by abwaters** [comment]
Lol...i'm going to have to think about it but for now, it works so i'll 
go with that.  Thanks Caleb!
