### ISSUE TITLE
mouseMoveOutside

### ISSUE THREAD

**Issue by rrusconi** [caleb531/jcanvas#241]
Exist in jcanvas a function like EASELJS.mouseMoveOutside ?
thanks

**Comment by caleb531** [comment]
jCanvas has a `mouseout` event which should do what you want:
http://projects.calebevans.me/jcanvas/docs/mouseEvents/#the-mouseover-and-mouseout-events

**Comment by rrusconi** [comment]
Tank you Evans 
I try to explain my problem
I would like make a scrollbar plugin, it works, but when the mouse pointer accidentally go out the canvas ... the scroll operation stop to work
Is there a solution for this ?

**Comment by caleb531** [comment]
Ah, that's quite a different problem. Fortunately, there is indeed a solution.

Internally, jCanvas binds a `mouseout` event to the canvas which cancels layer dragging when fired. To fix this, simply unbind the event handler like so:

```js
$('#myCanvas').off('mouseout.jCanvas');
```

**Comment by rrusconi** [comment]
Ok. 
thank you for your answer
In the final solution, i would like to keep dragging of my scrollbar, even if I am outside the canvas
Any suggestion for this ?

**Comment by caleb531** [comment]
Unfortunately, to do *that*, you will need to bind event listeners to the entire page (with jQuery's `.on()` method), and then write the dragging logic yourself. This is because jCanvas only binds its event listeners to the canvas itself—it doesn't listen to any events that take place outside the canvas.

Here's an example I conjured up for you; you can run it in the [jCanvas Sandbox](http://projects.calebevans.me/jcanvas/sandbox/). I've done a lot of the work for you, but it's still only a partial solution; you can drag anywhere on the canvas to move the circle. I leave it to you to decide how you want to calculate if the cursor intersects with your layer based on the shapes you are working with.

```js
var $canvas = $('canvas');

$canvas.drawArc({
  layer: true,
  name: 'mycircle',
  fillStyle: '#000',
  x: 100, y: 100,
  radius: 50
});

// Retrieve the current mouse coordinates releative to the given element
function getEventCoords($elem, event) {
  var offset = $elem.offset();
  return {
    x: event.pageX - offset.left,
    y: event.pageY - offset.top
  };
}

function enableTranscendentDrag($canvas, layerId) {

  var $document = $(document);

  var layer = $canvas.getLayer(layerId);
  var startX, startY, endX, endY;
  var dragging = false;

  $document.on('mousedown', function (event) {
    if (event.target === $canvas[0]) {
      var eventCoords = getEventCoords($canvas, event);
      startX = layer.x;
      startY = layer.y;
      endX = eventCoords.x;
      endY = eventCoords.y;
      dragging = true;
    }
  });
  $document.on('mousemove', function (event) {
    if (dragging) {
      var eventCoords = getEventCoords($canvas, event);
      var newX = eventCoords.x - (endX - startX);
      var newY = eventCoords.y - (endY - startY);
	  layer.x = newX;
	  layer.y = newY;
	  $canvas.drawLayers();
    }
  });
  $document.on('mouseup', function () {
  	dragging = false;
  });

}
enableTranscendentDrag($canvas, 'mycircle');
```

**Comment by rrusconi** [comment]
Thank you so much for the example.
I think you should be include this feature in jcanvas (EASELJS do it with a simple property: mouseMoveOutside=true )
