### ISSUE TITLE
IE11 blinking layers

### ISSUE THREAD

**Issue by shimbala** [caleb531/jcanvas#242]
HI, 

If you run this code in IE11 and the click few times DUPLICATE, you will get blinking layers and if you start to drag them... well it looks strange. In other browsers everything is fine.

Is there some fix for this kind of bug/error/..

[Link](http://projects.calebevans.me/jcanvas/sandbox/?code=JCgnY2FudmFzJykKCS5kcmF3SW1hZ2UoewoJCWxheWVyOiB0cnVlLAoJCXZpc2libGU6IHRydWUsCgkJZ3JvdXBzOiBbJ2xheWVyX2ltZ1NwcmVkbmphU3RyYW4nLCAnaW1nUHJlbWlrYWpTa3VwYWonXSwKCQlkcmFnR3JvdXBzOiBbJ2ltZ1ByZW1pa2FqU2t1cGFqJ10sCgkJZHJhZ2dhYmxlOiB0cnVlLAoJCW5hbWU6ICdpbWdTcHIxJywKCQlzb3VyY2U6ICdodHRwOi8vZHVtbXlpbWFnZS5jb20vNjAweDYwMC9DQ0MvZmZmJywKCQlkcmFnOiBmdW5jdGlvbihsYXllcikgewoJCQkvL2ZuQ2hlY2tJbWdQb3NpdGlvbihsYXllcik7CgkJfSwKCQljdXJzb3JzOiB7CgkJCW1vdXNlb3ZlcjogJ3BvaW50ZXInLCAvLyBTaG93IHBvaW50ZXIgb24gaG92ZXIKCQkJbW91c2Vkb3duOiAnbW92ZScsIAkJLy8gU2hvdyAnbW92ZScgY3Vyc29yIG9uIG1vdXNlZG93bgoJCQltb3VzZXVwOiAncG9pbnRlcicgCQkvLyBSZXZlcnQgY3Vyc29yIG9uIG1vdXNldXAKCQl9LAoJCXg6IDIyMCwgCgkJeTogMjIwLAoJCXNjYWxlOiAxLAoJCXdpZHRoOiAyMDAsIAoJCWhlaWdodDogMjAwCgl9KQoJLmRyYXdJbWFnZSh7CgkJbGF5ZXI6IHRydWUsCgkJdmlzaWJsZTogdHJ1ZSwKCQlncm91cHM6IFsnbGF5ZXJfaW1nU3ByZWRuamFTdHJhbicsJ2ltZ1ByZW1pa2FqU2t1cGFqJ10sCgkJZHJhZ0dyb3VwczogWydpbWdQcmVtaWthalNrdXBhaiddLAoJCWRyYWdnYWJsZTogdHJ1ZSwKCQluYW1lOiAnaW1nU3ByMicsCgkJc291cmNlOiAnaHR0cDovL2R1bW15aW1hZ2UuY29tLzYwMHg2MDAvMDAwL2ZmZicsCgkJZHJhZzogZnVuY3Rpb24obGF5ZXIpIHsKCQkJLy9mbkNoZWNrSW1nUG9zaXRpb24obGF5ZXIpOwoJCX0sCgkJY3Vyc29yczogewoJCQltb3VzZW92ZXI6ICdwb2ludGVyJywgLy8gU2hvdyBwb2ludGVyIG9uIGhvdmVyCgkJCW1vdXNlZG93bjogJ21vdmUnLCAvLyBTaG93ICdtb3ZlJyBjdXJzb3Igb24gbW91c2Vkb3duCgkJCW1vdXNldXA6ICdwb2ludGVyJyAvLyBSZXZlcnQgY3Vyc29yIG9uIG1vdXNldXAKCQl9LAoJCXg6IDI0MCwgCgkJeTogMjQwLAoJCXNjYWxlOiAxLAoJCXdpZHRoOiAyMDAsIAoJCWhlaWdodDogMjAwCgl9KTs=)

Cheers, Erik

**Comment by caleb531** [comment]
A few things:

1. Try [using an img DOM element](http://projects.calebevans.me/jcanvas/docs/images/#using-an-image-element) as a value for the `source` property (instead of a string URL).

2. Instead of using `drawImage()`, use `addLayer()` with `type: 'image'`, followed by `drawLayers()`. Using the former solution (`drawImage()`) draws the images immediately even if previous images have not finished loading (effectively resulting in a race condition). By using `addLayer()` in conjunction with `drawLayers()`, jCanvas will intelligently delay drawing of each image until any previous images have loaded.

Caleb

**Comment by shimbala** [comment]
Hi, 

thank you for response... Using an img DOM element solved my problem (and also the other one I was having throuble with).

Cheers, Erik
