### ISSUE TITLE
.css('cursor') is being reset on mouse move

### ISSUE THREAD

**Issue by arrowd** [caleb531/jcanvas#243]
In the `click` event of one of my layers i have `$('canvas').css('cursor', 'crosshair')`. When i make a click, the cursor changes to crosshair, but once the cursor leaves the element, it gets back to "auto". Is this intended behavior and how to preserve the property value?

**Comment by caleb531** [comment]
Try using jCanvas's `cursors` property instead of setting via CSS:
http://projects.calebevans.me/jcanvas/docs/eventProperties/#the-cursors-property

Caleb

**Comment by arrowd** [comment]
The crosshair still reverts to "auto" when i move a pointer out of the element. What i want is to have crosshair cursor on whole canvas until user clicks something else.

**Comment by caleb531** [comment]
Ah, I see.

In that case, I recommend this: instead of setting `cursor: 'crosshair'` via jQuery's `css()` method, use `addClass` to add some class to the canvas element. Then, add a declaration for that class in CSS that uses `!important` to override jCanvas's cursor value.

Something like:

CSS:
```css
.cursor-crosshair {
    cursor: crosshair !important;
}
```

JavaScript:
```js
$('canvas').addClass('cursor-crosshair');
```

**Comment by arrowd** [comment]
Yes, that worked, thanks. The issue can be closed, i guess.
