### ISSUE TITLE
Accessing to the width of a layer

### ISSUE THREAD

**Issue by thingNumber1** [caleb531/jcanvas#246]
Ok, I don't wanna to bother that much but when I use `console.log($('canvas').getLayer('backgroundImage'));` I can see and object and the `width` is there, but if I use `console.log($('canvas').getLayer('backgroundImage').width);` I get `NULL`. How can I know the widht of the certain layer (image type).

**Comment by caleb531** [comment]
Images in jCanvas are loaded and drawn asynchronously. Therefore, the width and height for image layers will not be accessible until the image has fully loaded.

To solve this, you can specify a `load` callback for your image that is run whenever the image is drawn. Since I figure you only want to run this logic once, you can use a boolean to prevent the loop

```js
var imageLoaded;
$('canvas').drawImage({
  layer: true,
  source: 'images/ladybug.jpg',
  x: 150, y: 150,
  load: function(layer) {
    if (!imageLoaded) {
      imageLoaded = true;
      // layer.width and layer.height will now be set
    }
  }
});
```

For efficiency, you may wish to use a DOM element as the value for the `source` property like so:

```js
$('canvas').drawImage({
  // ...
  source: $('#myladybug')[0]
  // ...
});
```
