### ISSUE TITLE
On canvas scale a handle doesn't scale correctly

### ISSUE THREAD

**Issue by jordan-enev** [caleb531/jcanvas#248]
Hello,

Let's use [my previous issue](https://github.com/caleb531/jcanvas/issues/247) as a base example.
But now on the button click I want dynamically add a Handle (for resizing the rectangle layer).

The problem is that the Handle doesn't scale correctly on the buttons click - Zoom in/out. On Zoom reset (_scale=1_) - it's okay.

Here is a [JSFiddle ](https://jsfiddle.net/jordan_enev/kj1d60ze/)that reproduces the problem.

Thank you! :)

**Comment by caleb531** [comment]
Handles are added to the end of the list of layers internally, but in order for the scaling to work correctly, you need the `restoreCanvas` layer to *always* be the last layer. This is why the handles aren't scaled up, because the handles are being added *after* that `restoreCanvas` layer.

You need to add the handles initially and hide them with setLayerGroup. Then, you can simply make them visible again using setLayerGroup in your event callback.
https://jsfiddle.net/kj1d60ze/11/
