### ISSUE TITLE
setLayers() filtering function doesn't see .data property

### ISSUE THREAD

**Issue by arrowd** [caleb531/jcanvas#249]
I have some layers created as

```
canvas.drawLine({
...
data: {edge: edge},
...
});
```

When I inspect `canvas.getLayers()` i can see that created lines have `data` property correctly set.

Now i do `canvas.setLayers({}, function(layer) {console.log(layer.data); return true;}` and this always yields an empty object.

**Comment by caleb531** [comment]
Strange, because it works for me perfectly in the [jCanvas Sandbox](http://projects.calebevans.me/jcanvas/sandbox/):

![screen shot 2016-07-13 at 9 50 01 am](https://cloud.githubusercontent.com/assets/872474/16811890/5b75c70c-48df-11e6-822a-d046a6f99ba8.png)

Can you please try writing a test case in the Sandbox that reproduces the issue?

Thanks,
Caleb

**Comment by arrowd** [comment]
Apparently, this was indeed a error on my side. Sorry for the fuss.
