### ISSUE TITLE
Draglayers position lagging one event behind on drag

### ISSUE THREAD

**Issue by arjenrschat** [caleb531/jcanvas#264]
Hi Caleb,

It look like drawlayers uses the old layer postion from before a drag event.

I noticed that:
The dragged layer/ handle snaps into place on the mouseup.
You can make the dragged layer move in opposite direction of the mouse when you repeatedly move your mouse one pixel to the left and right.
The layer postion is not updated on the first move related event.

This behavior is present on https://projects.calebevans.me/jcanvas/docs/draggableLayers/

BTW - Jcanvas is awesome.

**Comment by caleb531** [comment]
Yes, this is a known behavior. However, this will not be changing because it is inherent with how I've written jCanvas: all layer events are handled after layers are redrawn (not before), as important event information can only be computed when the layer is drawn. Changing this behavior would require a substantial rewrite of jCanvas, which I am not ready or prepared to do at this time.
