### ISSUE TITLE
measureText doesn't consider spaces at the end of the text

### ISSUE THREAD

**Issue by arrowd** [caleb531/jcanvas#267]
I am rendering text with markdown-like marks (`**` for bold only) using jCanvas. For this, I am splitting the text into chunks and then use `.drawText()` shifting `x` coordinate by `measureText('previousChunk')`. This works well except for case when whole word is bolded, like `normal **bold**`.

My code splits above text into `["normal ", "**bold**"]`, but measureText doesn't consider space character in first case. Rendering `normal** bold**` works fine.

I've tracked the problem to these lines: https://github.com/caleb531/jcanvas/blob/master/jcanvas.js#L3600
What's rationale in removing spaces at the end of the string? How can my case be fixed or workarounded?

**Comment by arrowd** [comment]
Just as note: calling `measureText` for JavaScript's canvas context yields proper result.

**Comment by caleb531** [comment]
> What's rationale in removing spaces at the end of the string?

Good question; I honestly can't remember why I did that; maybe I thought it might be convenient at the time, but if that was the case, why am I also not removing leading whitespace? As far as I can tell, it's not really necessary.

To be clear: can you confirm that the jCanvas `measureText()` method returns the expected values when you remove that single line?

**Comment by caleb531** [comment]
Oh, I remember now. The comment gives a hint to my original thinking:

```
// Remove extra space at the end of each line
allLines = allLines.concat(
	lines
	.join( '\n' )
	.replace( /( (\n))|( $)/gi, '$2' )
	.split( '\n' )
);
```

Therefore, if I recall my reasoning correctly, the trailing-whitespace-trimming was added for the sake of line wrapping. That is, I reasoned that a trailing space at the end of a line should not count toward the width of the line (because a trailing space triggers a break to a new line, so the space isn't needed and perhaps shouldn't be counted).

Thoughts?

**Comment by arrowd** [comment]
> Therefore, if I recall my reasoning correctly, the trailing-whitespace-trimming was added for the sake of line wrapping. That is, I reasoned that a trailing space at the end of a line should not count toward the width of the line (because a trailing space triggers a break to a new line, so the space isn't needed and perhaps shouldn't be counted).

I fully agree with that, but current implementation also trims spaces even when no wrapping is required and text is short enough to fit into `maxWidth`. And this is where things break for me.

I can workaround this with something roughly like `measureText("a a").width - measureText("a").width * 2`, so it is OK if things will remain as they are.

**Comment by caleb531** [comment]
Alright, then. Personally, I'm inclined to keep the current behavior (trimming regardless of wrapping), especially since you have a very particular use case.

For what it's worth, you can eliminate one of those calls to `measureText()` by just passing a single space to `measureText` (*e.g.* `measureText(' ').width`). I just tried it now in Chrome and Firefox, with success in both browsers.
