### ISSUE TITLE
IE11 and Edge do not include stroke when listening for mouse events

### ISSUE THREAD

**Issue by jimd33463** [caleb531/jcanvas#314]
Using the simple example below (copy paste into jCanvas website Sandbox), you'll see that in Chrome you can click on the stroke to activate the animation.  However in IE and Edge you have to click within the fill.   Does anyone know if there's a work-around for this?  Thanks

// Click the star to make it spin
$('canvas').drawPolygon({
  layer: true,
  fillStyle: '#c33',
  strokeStyle: 'rgba(0,0,0,.5)',
  strokeWidth: 20,
  x: 150, y: 150,
  radius: 100,
  sides: 20,
  concavity: .02,
  click: function(layer) {
    // Spin star
    $(this).animateLayer(layer, {
      rotate: '+=144'
    });
  }
});

**Comment by caleb531** [comment]
Unfortunately, there is no pretty workaround. IE11 (and seemingly Edge too, sadly) do not support the HTML5 isPointInStroke canvas method, which jCanvas uses to enable the behavior of triggering events on drawing strokes.

Since you are using polygons, you *could* work around this by using two overlapping polygons. The one beneath would act as the stroke, and the other (slightly smaller) polygon would act as the fill. If you need these polygons to be draggable as a single unit, use the [drag groups](https://projects.calebevans.me/jcanvas/docs/draggableLayers/#drag-groups) feature of jCanvas.

**Comment by jimd33463** [comment]
Thanks very much for the responses to my inquires!  I'll give that a try.  Is there some sort of 'scale' property available that would scale up a layer?  I need the layer scaled up to mimic a 3-pixel stroke.

**Comment by caleb531** [comment]
@jimd33463 The value for the `scale` property should be a number like `1.05`, not `(1.05, 1.05)` or even `[1.05, 1.05]`. If you want to control the scale axes separately, use `scaleX` and `scaleY`.

https://projects.calebevans.me/jcanvas/docs/scaleCanvas/#the-scale-property
