### ISSUE TITLE
Detect if point coordinate is on a shape

### ISSUE THREAD

**Issue by jimd33463** [caleb531/jcanvas#315]
I'm looking for a way to detect if a given point coordinate is within on a shape.  I was looking at the "IsPointInPath" property, but having trouble implementing that with jCanvas.

The following does not work. Any help would be appreciated...

// retrieve a previously drawn layer and see if point is within it
var layr = $('canvas').getLayer('A');
var isTouching = layr.isPointInPath(353,402);

**Comment by caleb531** [comment]
`isPointInPath()` is a native canvas context method, but it is *not* a jCanvas method, and it does not work with layers. The closest thing you can do is read the `intersects` property on a given layer, which will be `true` if the current cursor coordinates lie within that layer (since the last redraw):

```js
var layer = $('canvas').getLayer('A');
var isTouching = layer.intersects;
```

See the docs: https://projects.calebevans.me/jcanvas/docs/properties/#intersects
