### ISSUE TITLE
Hi, Caleb, I'm not quite understand this passage, the first part of Animating Layers.

### ISSUE THREAD

**Issue by vrbvillor** [caleb531/jcanvas#318]
A callback function that runs when the animation completes (optional). It accepts the following arguments: - The percentage of the animation which has completed (as a value from 0 to 1). - A jQuery.fx object containing properties related to the animation. - The layer being animated.

I'm reorganizing the documentation of the jCanvas. And see this new words of Animating Layers. It says the callback function receives `3` parameters, but the demo script only show it receives one -- the layer object. Could you explain this for me? Thanks.  ^3^

**Comment by vrbvillor** [comment]
![image](https://user-images.githubusercontent.com/8016761/34515988-c672ba32-f0af-11e7-89b3-a559451c36a7.png)

The doc has some error. Please check it.

**Comment by vrbvillor** [comment]
https://projects.calebevans.me/jcanvas/docs/mouseEvents/#the-mouseover-and-mouseout-events

The mouseover and mouseout events demo is not correct. The comment in the code is to say to rotate the triangle but the final effect is only change the fillStyle.

**Comment by vrbvillor** [comment]
https://projects.calebevans.me/jcanvas/docs/mechanicalEvents/#the-move-event

The demo code of move event is not clear enough.

**Comment by vrbvillor** [comment]
And all mechnical event use a primary verb, except delay uses `delayed`.

**Comment by vrbvillor** [comment]
By the way, how to draw a vector path icon, such as icon font with a complex paths??

For example.
```
M21.2,63C21.2,63,4.2,55.8,-10.6,53.6C-10.6,53.6,-27.2,51,-43.8,58.2C-43.8,58.2,-56,64.2,-61.4,74.4
```

**Comment by caleb531** [comment]
Hi, @vrbvillor. From the top:

1. You are absolutely correct; the three arguments refers to the `step` callback, not `complete`; I have corrected this in the docs and pushed the changes.
2. Yes, it should be *stop\** instead of *delay\**; I've corrected this too
3. I've clarified the examples and descriptions for the whole Mechanical Events page
4. *facepalm* How did I miss that? The callback name definitely should be `delay`, not `delayed`. Thanks for catching that.
5. No, jCanvas does not support SVG path syntax. However, you can replicate an SVG path more-or-less exactly using the `drawPath()` method: https://projects.calebevans.me/jcanvas/docs/paths/
