### ISSUE TITLE
Handle plugin missing advanced feature - Rotation Handle

### ISSUE THREAD

**Issue by Roinoss** [caleb531/jcanvas#347]
I think handle plugin should have option to use additional handle to rotate content.

```
      O                  <- rotation handle
  O___|___O
  |       |
  O-------O
```

**Comment by caleb531** [comment]
@Roinoss I've considered this in the past, and have actually tried to implement this fully—for that, check out the [feature-handles-rotation](https://github.com/caleb531/jcanvas/tree/feature-handles-rotation) branch—but it is challenging to get right. I've since postponed development on that functionality for the time being, but you are welcome to view the code on that branch to use what's there and perhaps even improve upon it (if you're feeling so kind and adventurous).
