### ISSUE TITLE
jcanvas21.0.1 in fireFox(70.0.1 ) removeLayer() and removeLayers() has bug

### ISSUE THREAD

**Issue by 348339749** [caleb531/jcanvas#351]
jcanvas21.0.1 in fireFox(70.0.1 ) when i use removeLayer() or removeLayers(),i have to move mouse out of canvas, or double click on layer  to delete this layer . this is my code:
$("canvas").drawPolygon({
  fillStyle: "#6c3",
  x: 100, y: 100,
  radius: 50, sides: 5,
  layer:true,
  click:function(layer){
    $("canvas").removeLayer(layer);
  }
});

first click (mousedown,mouseup) nothing change,move out or click again ,the layer will remove.

**Comment by caleb531** [comment]
@348339749 You must call drawLayers() after calling removeLayer() to redraw the canvas. So your modified example would become:

```js
$("canvas").drawPolygon({
fillStyle: "#6c3",
x: 100, y: 100,
radius: 50, sides: 5,
layer:true,
click:function(layer){
$("canvas").removeLayer(layer).drawLayers();
}
});
```

The reason your code works when you mouse out of the canvas is because jCanvas automatically redraws the canvas upon mouseout. But in this particular instance, you must redraw the canvas manually after removing the layer.
