### ISSUE TITLE
Export Canvas: Excluding certain objects

### ISSUE THREAD

**Issue by nico-apps** [caleb531/jcanvas#366]
I'm using a mix of jCanvas and vanilla JS to create a Whiteboard application. I also want to include rectangles and other shapes, and since I want the application to be as user-friendly as possible, I thought having them draggable would be a good idea. Therefore I decided to include jCanvas into my project. And after fiddling around a bit, I created a script that works pretty well, you can check it out [here](http://montemanager.de/whiteboardApp.php). Problem is, when dragging the rect around, it duplicates since my exporting function also exports the rect. Would it be possible to have a function which doesn't export a specific rect or something like that?

Thanks in advance

**Comment by caleb531** [comment]
@nico-apps It's probably because you are creating the rectangle as a layer (on line 148 in `whiteboardApp.php`):

```js
$("#can").drawRect({
    layer: true,
    draggable: true,
    bringToFront: true,
    // ...
```

Because the rectangle is a layer, when the canvas is redrawn (which can happen automatically when you mousedown/mouseup on the canvas), then that layer gets redrawn as well, and will likely get captured in your image capture of the canvas. You could make the shape no longer a layer, however that would remove the draggable capability.

You should either:

1. Embrace the jCanvas Layers API and let it do the redrawing for you. This means you don't need to capture an image of the canvas to save the state; you can simply create a `drawLine` layer and just update the paths to create the free-form painting effect. Same for the rectangles
2. Remove the `layer: true` and `draggable: true` from your `drawRect` on line 147, but this means you must perform the dragging / mouse event calculations yourself.

**Comment by nico-apps** [comment]
Hi @caleb531, I'm sorry for answering so late.

Thank you for your help! I chose option 1, and it works greatly. I only have one problem:

As it turns out, I can only change the width and height of the canvas by assigning a specific pixels number (`250 px` for example). Whenever I try to use a percentage (to make it work on mobile devices as well), jCanvas doesn't get the right scope. Here is a gif to show you what I mean:

![Neues Whiteboard - Google Chrome 2021-04-25 16-41-10](https://user-images.githubusercontent.com/35093969/115998052-c0763c00-a5e5-11eb-9a83-79514c009c31.gif)

Just like drawing the rectangle, I'm also using jCanvas to draw the lines. Do you know how I could resize the canvas depending on the size of the device used?

Thanks in advance

**Comment by caleb531** [comment]
@nico-apps I recommend you calculate the precise pixel value to use for setting the `width`/`height` using `window.innerWidth` and `window.innerHeight` and such. Using CSS percentages would definitely be too unpredictable. Let JS do the math for you.

**Comment by nico-apps** [comment]
Thank you @caleb531 ! That helped!
